services:
  eshop_catalog-db:
    image: postgres
  
  eshop_basket-db:
    image: postgres
    
  eshop_redis:
    image: redis
  
  eshop_catalog-api:
    image: eshop_catalog-api
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

  eshop_basket-api:
    image: eshop_basket-api
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

volumes:
  postgres_eshop_catalog:
  postgres_eshop_basket:
