version: "3.4"

services:
  eshop_catalog-db:
    container_name: eshop_catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=EShop_Catalog
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshop_catalog:/var/lib/postgresql/data/

volumes:
  postgres_eshop_catalog: